# https://aka.ms/yaml

trigger:
- master

variables:
  versionHadolint: 'v1.16.3'
  versionBuilder: 'latest'

stages:
  - stage: lint
    jobs:
      - job: 'Hadolint'
        pool:
          vmImage: 'ubuntu-16.04'
        steps:
        - script: sudo docker pull hadolint/hadolint:$(versionHadolint)
          displayName: 'Install Hadolint'
        - script: |
            set -e
            shopt -s globstar
            for dockerfile in **/Dockerfile
            do
              echo "Linting: $dockerfile"
              sudo docker run --rm -i \
                -v $(pwd)/.hadolint.yaml:/.hadolint.yaml:ro \
                hadolint/hadolint:$(versionHadolint) < "$dockerfile"
            done
          displayName: 'Run Hadolint'

      - job: 'JQ'
        pool:
          vmImage: 'ubuntu-16.04'
        steps:
        - script: sudo apt-get install -y jq
          displayName: 'Install JQ'
        - bash: |
            shopt -s globstar
            cat **/*.json | jq '.'
          displayName: 'Run JQ'
  - stage: build
    dependsOn: lint
    jobs:
      - template: .azure-pipelines/job-matrix.yml
        parameters:
          matrix:
            - addon: znc
              jobName: znc
              arch: '--armhf --amd64 --aarch64'
            - addon: hydra2
              jobName: hydra2
              arch: '--armhf --amd64 --aarch64'
            - addon: nzbget
              jobName: nzbget
              arch: '--armhf --amd64 --aarch64'
            - addon: sonarr
              jobName: sonarr
              arch: '--armhf --amd64 --aarch64'
            - addon: radarr
              jobName: radarr
              arch: '--armhf --amd64 --aarch64'
            - addon: emby
              jobName: emby
              arch: '--armhf --amd64 --aarch64'
            - addon: jellyfin
              jobName: jellyfin
              arch: '--armhf --amd64 --aarch64'
            - addon: jackett
              jobName: jackett
              arch: '--armhf --amd64 --aarch64'
            - addon: transmission-openvpn
              jobName: transmission_openvpn
              arch: '--amd64'
            - addon: transmission-magnet-redirect
              jobName: transmission_magnet_redirect
              arch: '--amd64'
            - addon: hyperion
              jobName: hyperion
              arch: '--armhf --amd64 --aarch64'