#!/usr/bin/with-contenv bash

if [ ! -f /ssl/fullchain.pem ]; then
  echo "No Home Assistant SSL certificates found, changing paths for self-generated certificates" && \
  mkdir -p /config/heimdall/keys && \
  sed -i "s|/ssl/fullchain.pem|/config/heimdall/keys/cert.crt|g" /defaults/nginx/*.sample && \
  sed -i "s|/ssl/privkey.pem|/config/heimdall/keys/cert.key|g" /defaults/nginx/*.sample && \
  sed -i "s|/ssl/fullchain.pem|/config/heimdall/keys/cert.crt|g" /config/heimdall/nginx/site-confs/* && \
  sed -i "s|/ssl/privkey.pem|/config/heimdall/keys/cert.key|g" /config/heimdall/nginx/site-confs/* && \
  sed -i "s|/ssl/fullchain.pem|/config/heimdall/keys/cert.crt|g" /etc/cont-init.d/* && \
  sed -i "s|/ssl/privkey.pem|/config/heimdall/keys/cert.key|g" /etc/cont-init.d/* && \
  sed -i "s|/ssl|/config/heimdall/keys|g" /etc/cont-init.d/*
else
  echo "Home Assistant SSL certificates found" && \
  sed -i "s|/config/heimdall/keys/cert.crt|/ssl/fullchain.pem|g" /config/heimdall/nginx/site-confs/* && \
  sed -i "s|/config/heimdall/keys/cert.key|/ssl/privkey.pem|g" /config/heimdall/nginx/site-confs/*
fi