parameters:
    jobName:
    addon: 
    arch: '--armhf --amd64 --aarch64'
    poolVmImage: 'ubuntu-16.04'

jobs:
  - job: ${{ parameters.jobName }}
    displayName: ${{ parameters.addon }} 
    pool:
      vmImage: ${{ parameters.poolVmImage }}
    steps:
    - template: addon-template.yml
      parameters:
        addon: ${{ parameters.addon }}
        arch: ${{ parameters.arch }}
        ${{ if ne(variables['Build.SourceBranchName'], 'master') }}:
          additionalArgs: --test