# This azure pipeline template build add-ons

parameters:
  addon: ''
  arch: ''

steps:
  - task: Docker@2
    inputs:
      containerRegistry: 'DockerHub'
      command: 'login'
    displayName: 'DockerHub login'
  - script: sudo docker pull homeassistant/amd64-builder:$(versionBuilder)
    displayName: 'Install Builder'
  - script: |
      sudo docker run --rm --privileged \
        -v ~/.docker:/root/.docker \
        -v /run/docker.sock:/run/docker.sock:rw -v $(pwd):/data:ro \
        homeassistant/amd64-builder:$(versionBuilder) \
        --addon ${{ parameters.arch }} -t /data/${{ parameters.addon }} \
        --docker-hub petersendev --docker-hub-check
    displayName: 'Build ${{ parameters.addon }}'